# Generated by Django 3.2.5 on 2021-07-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_user'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movies_watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='movies.Movie'),
        ),
    ]
