# Generated by Django 3.2.5 on 2021-07-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='movies.Rating'),
        ),
    ]
